# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
version: 2
# SPHINX SETTINGS
sphinx:
  builder: html
  configuration: docs/source/conf.py
# BUILD FORMATS
formats: all

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.8"

python:
  install:
    - requirements: docs/requirements.txt
    - method: setuptools
      path: .

submodules:
  include: all
  recursive: true
